# head
YOLO_NOSE = 0
YOLO_LEFT_EYE = 1
YOLO_RIGHT_EYE = 2
YOLO_LEFT_EARS = 3
YOLO_RIGHT_EARS = 4

YOLO_LEFT_SHOULDER = 5
YOLO_RIGHT_SHOULDER = 6

YOLO_LEFT_ELBOW = 7
YOLO_RIGHT_ELBOW = 8

YOLO_LEFT_WRIST = 9
YOLO_RIGHT_WRIST = 10

YOLO_LEFT_HIP = 11
YOLO_RIGHT_HIP = 12

YOLO_LEFT_KNEE = 13
YOLO_RIGHT_KNEE = 14

YOLO_LEFT_ANKLE = 15
YOLO_RIGHT_ANKLE = 16